version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: no
    expose:
      - "3000"

  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: no
    environment:
      - PORT=8001
    expose:
      - "8001"
    depends_on:
      - mongo

  backend2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: no
    environment:
      - PORT=8002
    expose:
      - "8002"
    depends_on:
      - mongo

  backend3:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: no
    environment:
      - PORT=8003
    ports:
      - "8003:8003"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: no
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend1
      - backend2
      - backend3

volumes:
  mongo-data:
